#!/bin/bash

# Add the user to a file in sudoers.d if they're not already in sudoers
if ! grep -q threatos /etc/sudoers; then
    echo 'threatos ALL=(ALL) NOPASSWD: ALL' >>/etc/sudoers.d/threatos-user

fi
