name: Build and Test

on:
  push:
    branches:
      - threatos-arm

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install Prerequisites
        run: |
          sudo python -m pip install --upgrade pip
          sudo pip install -r docs/requirements.txt

      - name: Lint YAML
        run: yamllint devices.yml

  generate_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Prerequisites
        run: |
          sudo python -m pip install --upgrade pip
          sudo pip install -r docs/requirements.txt
          sudo apt-get update
          sudo apt-get -y install pandoc

      - name: Generate Documentation
        run: |
          sudo ./bin/generate_devices_stats.py
          sudo ./bin/generate_devices_table.py
          sudo ./bin/generate_images_overview.py
          sudo ./bin/generate_images_stats.py
          sudo ./bin/generate_images_table.py
          sudo ./bin/generate_kernel_stats.py
          sudo mkdir -pv ./public/
          sudo cp -v ./docs/404.html   ./public/
          sudo cp -v ./docs/public.css ./public/
          sudo pandoc --standalone ./docs/www.md    --css=public.css --include-in-header=./docs/header.html --output=./public/index.html
          sudo pandoc --standalone ./device-stats.md   --css=public.css --include-in-header=./docs/header.html --output=./public/device-stats.html
          sudo pandoc --standalone ./devices.md        --css=public.css --include-in-header=./docs/header.html --output=./public/devices.html
          sudo pandoc --standalone ./image-overview.md --css=public.css --include-in-header=./docs/header.html --output=./public/image-overview.html
          sudo pandoc --standalone ./image-stats.md    --css=public.css --include-in-header=./docs/header.html --output=./public/image-stats.html
          sudo pandoc --standalone ./images.md         --css=public.css --include-in-header=./docs/header.html --output=./public/images.html
          sudo pandoc --standalone ./kernel-stats.md   --css=public.css --include-in-header=./docs/header.html --output=./public/kernel-stats.html
      

      - name: Archive Documentation
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ./public
